### PR TITLE
Consolidate bibtex files into one.

### LINKED ISSUE #135: Consolidate bibtex files
We currently have bibtex files all over the place:

```
./datasets/sources.bib
./phylogenies/bouckaert_et_al2012/source.bib
./phylogenies/bowern_and_atkinson2012/source.bib
./phylogenies/chacon_and_list2015/source.bib
./phylogenies/chang_et_al2015/source.bib
./phylogenies/dunn_et_al2011_utoaztecan/source.bib
./phylogenies/gray_et_al2009/source.bib
./phylogenies/grollemund_et_al2015/source.bib
./phylogenies/honkola_et_al2013/source.bib
./phylogenies/kitchen_et_al2009/source.bib
./phylogenies/lee_and_hasegawa2011/source.bib
./phylogenies/michael_et_al2015/source.bib
./phylogenies/sicoli_and_holton2014/source.bib
```

i.e. datasets/ has a combined sources.bib, while each phylogeny has a single source.bib. 

Should we consolidate these into a single sources.bib, perhaps in its own top level file (./sources.bib)? or keep them as dataset specific resources?

### PR DESCRIPTION
**Pull request by SimonGreenhill**
Fixes #135

### CODE REVIEW

**Comment by xrotwang** [comment]
Will merge after adapting `pydplace`.

**Comment by xrotwang** [comment]
as far as I can tell, the `sources.bib` for individual phylogenies hasn't been used/accessed by the API at all so far. I think we should add a column `source_id` to `phylogenies/index.csv` to change this.

**Comment by xrotwang** [comment]
I think I'll even make a release of pydplace before merging this - just to make things reproducible.

**Comment by SimonGreenhill** [comment]
Looks like we should the glottlog reference to sources.bib as well.

**Comment by xrotwang** [comment]
Maybe - but then the glottolog ref is created automatically, so `sources.bib` would be one of the files that are edited by hand *and* code - which I found confusing whenever I ended up with such a situation.

**Pull request merged**
