### PR TITLE
Refactored EA, Binford and TEOW data

### PR DESCRIPTION
**Pull request by xrotwang**
The data of the EA and Binford datasets has been refactored according to
the spec laid out in https://github.com/D-PLACE/dplace-data/issues/21

TODO: Must adapt society IDs in `societies_mapping.csv`.

### CODE REVIEW

**Comment by xrotwang** [comment]
Don't merge yet. Will adapt D-PLACE data import first.

**Comment by SimonGreenhill** [comment]
Looks good! and scalable!

**Comment by xrotwang** [comment]
I'm in the process of refactoring the loading, and this unified data format and my favourite `attrs` library make the code much more transparent.

**Comment by SimonGreenhill** [comment]
Great -- merge it when you're ready

**Comment by SimonGreenhill** [comment]
Happy for me to merge?

**Comment by xrotwang** [comment]
Yes, I think this can be merged. Even in the worst case scenario of not merging the corresponding PR in D-PLACE/dplace it should be easy enough to adapt the loading process only.

**Pull request merged**
