### PR TITLE
Update api.py with url

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by xrotwang** [comment]
As is, this would turn `url` into a required attribute of `Phylogeny`, thus it would have to be present in `phylogenies/index.csv` (running `dplace check` now should fail). So either do this, or make it optional by adding a default value:
```python
    url = attr.ib(default=None)
```

**Comment by SimonGreenhill** [comment]
(sorry about the churn in glottolog.csv and summary.trees)

**Comment by SimonGreenhill** [comment]
added the rest of the urls

**Comment by SimonGreenhill** [comment]
no worries -- will create a new PR

**Pull request merged**
