### PR TITLE
fix Sources

### PR DESCRIPTION
**Pull request by xrotwang**
I'll just keep pushing more commits to this PR/branch

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Cool -- I'll let you merge this when you're ready.

**Comment by SimonGreenhill** [comment]
Hmm is [this comment](https://github.com/D-PLACE/dplace/blob/master/dplace_app/models.py#L246) still applicable? do we want to refactor this now?

**Comment by xrotwang** [comment]
@SimonGreenhill Regarding separating references and dataset sources: I think they should both use `Source` to store the bibliographic data. A `Source` turns into a dataset source by being related to a dataset, and into a reference by being related to a `Reference` - the future of the many-to-many relation between `Source` and `Value`.

**Comment by SimonGreenhill** [comment]
100% agree. Not sure how we ended up having two tables for this.

**Comment by xrotwang** [comment]
@SimonGreenhill I just turned the references into bibtex: https://github.com/D-PLACE/dplace-data/blob/70f98e3b6b81aa1babb3eb2fc123d33bbd93c286/datasets/sources.bib
I would hope, that this is a format a student assistant could work with. Tasks would be
- Find records with `citation_ea` **and** `citation_binford`, figure out if they are the same, if so, identifiy, i.e. complete the record and remove the `citation_*` fields. If not, leave as is.
- Find records without `glottolog_*` field and complete them.

About 3,300 records need a bit of work.
What do you think?

**Comment by SimonGreenhill** [comment]
I think it sounds like a good project. Can you make an issue for it, and I'll raise it at the meeting next week and see if we can get some action or help.

**Comment by xrotwang** [comment]
@SimonGreenhill https://github.com/D-PLACE/dplace-data/issues/86

**Comment by SimonGreenhill** [comment]
Thanks!

**Comment by xrotwang** [comment]
@SimonGreenhill  Finally the BibTeX is cleaned up (to a reasonable degree). So, I'd merge and then refactor the app. Do we have any deadlines? Any decisions taken at the workshop?

**Comment by SimonGreenhill** [comment]
Cool, thanks @xrotwang. I think everyone's happy to have a student assistant do this. No-one volunteered one, but we should try get one in Jena if possible. No deadlines, priority is to add the new datasets and fix the other bugs in front end. 

Merged :)

**Comment by xrotwang** [comment]
Thanks. Note that this requires already changes in the loader code, which
I'll get to tomorrow.
Am 18.04.2017 14:38 schrieb "Simon J Greenhill" <notifications@github.com>:

**Comment by kirbykat** [comment]
Thanks @xrotwang for all this work...

**Pull request merged**
