### PR TITLE
fixed value for society B356 and variable B004

### PR DESCRIPTION
**Pull request by xrotwang**
addresses #187

### CODE REVIEW

**Comment by kirbykat** [comment]
Thanks @xrotwang. Can we add an admin note to the change "20 Nov 2018 - Corrected based on values for B001, B002 and B003"?

**Comment by kirbykat** [comment]
@xrotwang I tried to make the above change. Suggestions on how to do this better are welcome (I'm still not comfortable editing csv files in GitHub, as you can no doubt tell).

**Comment by xrotwang** [comment]
@kirbykat where do you think you made the change? Ideally, you'd checkout the `issue187` branch, then make the change and commit and push the branch. Alternatively, you could go to the changes for this pull request, and edit these, here https://github.com/D-PLACE/dplace-data/pull/191/files

**Comment by xrotwang** [comment]
If you go to https://github.com/D-PLACE/dplace-data/pull/191/files , click the pencil icon to edit the file, then go to line 11130 and add the comment, then scroll down the page and click "commit directly to `issue187` branch", you should be done.

**Pull request merged**
