### PR TITLE
adding README.md files for phylogenies

### PR DESCRIPTION
**Pull request by SimonGreenhill**
Partially solves #113 (for phylogenies)

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
and added readmes for datasets. Closes #113

**Comment by SimonGreenhill** [comment]
README.md's nice as it's visible on github, it's easier to edit (multiple line content in csv files is painful) and it 'lives' with the data. The Binford README seems to work well, shall we use that system?

Do we want to rely on a template for these e.g. [https://d-place.org/phylogenys/gray_et_al2009](here) we have the citation in a big orange box, so something like:

```markdown

Phylogenies provided by $(author)s (%(year)s).  
Blah blah blah
See  [%(link)s](%(link)s).

If you use these please cite:

<pre>
%(citation)s
</pre>
```

Note: I've used `<pre>` here as this would be visible to the webapp (and stylable?)


(aside: the main reason I'm doing this is to provide an 'acknowledgements'

**Comment by xrotwang** [comment]
The biggest problem I see here, is that we *should* create this info from the data in `index.csv` - but I fully agree that not allowing editing README.md is hand is suboptimal. The alternative of parsing the sturctured data from a hand-edited README isn't appealing either.
So probably the best option would be to minimize overlap between the two data sources, and try to keep the duplicate info in sync (which should be doable, because all this is info that will only be changed to fix errors).

**Comment by SimonGreenhill** [comment]
Yes, I played around with the code in pydplace for this. 

I started trying to unify [Repos.datasets](https://github.com/D-PLACE/pydplace/blob/master/src/pydplace/api.py#L332) and [Repos.phylogenies](https://github.com/D-PLACE/pydplace/blob/master/src/pydplace/api.py#L351) to both load README.md but ran into the problem that we'd need a `description` column in all index.csv's (empty, yuck).  And `attrs` doesn't like having a default `description`.

```diff
+    def _iterdir(self, datatype):
+        # helper function to iterate over the {datasets, phylogenies} directory
+        if datatype == 'datasets':
+            Obj = Dataset
+        elif datatype == 'phylogenies':
+            Obj = Phylogeny
+        else:
+            raise ValueError("Unknown datatype %s" % datatype)
+        for r in reader(self.path(datatype, 'index.csv'), dicts=True):
+            ds = Obj(base_dir=self.path(datatype), **r)
             if not ds.description:
                 readme = ds.base_dir / ds.id / 'README.md'
                 if readme.exists():
                     ds.description = read_text(readme)
-        return res
+            yield ds
+
+    @lazyproperty
+    def datasets(self):
+        return self._iterdir('datasets')
+
+    @lazyproperty
+    def phylogenies(self):
+        return self._iterdir('phylogenies')
```

**Comment by SimonGreenhill** [comment]
Just going to close this for now, will reopen if it annoys me again.

**Pull request closed without merging**
