### PR TITLE
Fix environmental data

### LINKED ISSUE #151: Fix citation for environmental data
> My team and I have been hard at work locating new environmental data to fill in some important gaps in the current version of d-place and to correct what we perceive as limitations of the CRU TS v.3.3. data set. I am happy to announce today that we not only managed to do that, but were also able to get ahold of what we think are much better quality data sets than the ones we had (sources cited below for those that care about the details). Notably, the new variables provide FULL coverage (yes… that includes ALL societies for the info-pacific, which means no more limits on the environmental questions we ask!). Any way, attached are the data and source details. Enjoy!

A)  I’m not sure I know who to contact to update the data on D-PLACE (Simon… is that you or is it still Stephanie? Would you guys mind updating the web page with the new data? ALSO… could someone please update my lab’s web page in D-PLACE’s “team” url? It should be “https://pages.wustl.edu/botero", rather than "http://cabotero.weebly.com/“. Thanks!

B) I believe older variables with the same names as the ones provided here should no longer be distributed to avoid confusion (maybe they could be archived under something like “heritage data”?). The newer data is REALLY much better and we should discourage the use of the older one...

C) NEW DATA AND DATA SOURCES

1) Climate data

Annual mean, annual variance, predictability, constancy and contingency for both precipitation and temperature are now based on the “Baseline Historical (1900-1949), CCSM ecoClimate model”. The source citation is:

Lima-Ribeiro,M. et al. 2015. ecoClimate: a database of climate data from multiple models for past, present, and future for Macroecologists and Biogeographers
Biodiversity Informatics 10, 1-21. PDF

Please note that the definitions for these variables remain identical as what we currently have in D-PLACE but that the basic units for precipitation data are now grams per square meter per month. Big shout out to the folks at ecoClimate.org who kindly shared with us the raw data from their models (something that is not typically distributed to end users), allowing us to compute predictability, constancy and contingency just the way we wanted. 

2) Physical landscape

The current version of D-PLACE includes elevation and slope data from the GTOPO30 dataset (in fact, our current slope data were computed by Rick Step and he never shared with us the exact methods he used, so I am happy to switch to something I can completely vouch for). We have taken advantage of a newer and more accurate data source for elevation: the Global Multi-resolution Terrain Elevation Data 2010 (Link here: GMTED2010), which has replaced the GTOPO30 data over the years. Please note that elevation data from GMTED2010 comes at a whopping 30 ArcSec resolution (!!!) which I use to compute initial —highly local— estimates that are then down sampled to a 0.5 by 0.5 degree resolution in order to maintain consistency with all other D-PLACE variables.

Citation: Global Multi-resolution Terrain Elevation Data courtesy of the U.S. Geological Survey (Downloaded 14 Jul 2014 from http://topotools.cr.usgs.gov/gmted_viewer/)

### PR DESCRIPTION
**Pull request by xrotwang**
closes #151

### CODE REVIEW

**Comment by xrotwang** [comment]
@Bibiko are you going to make the corresponding changes on https://d-place.shh.mpg.de/source ?

**Comment by Bibiko** [comment]
I'll do.

**Comment by xrotwang** [comment]
@kirbykat As described here https://github.com/D-PLACE/dplace-data/blob/755dd654456d2126767502344d1291ec29c479a6/CHANGELOG.md I'd create a release of the status of this repository as it was published at the CES conference - mostly to keep a record of what was online. But then immediately create a bugfix release 1.1.1 containing the fixes from this pull request. Ok?

**Comment by kirbykat** [comment]
@xrotwang - this looks great - thanks

**Pull request merged**
