### PR TITLE
recreated glottolog 3.3 data, adding more info

### LINKED ISSUE #193: Glottolog trees must retain internal node names
It may be the case that D-PLACE societies are mapped to a Glottolog language and others to dialects of this language. Thus, the current practice of pruning full Glottolog family trees to leafs with D-PLACE mappings and then write the trees omitting internal node names is incorrect!

See also https://github.com/D-PLACE/pydplace/issues/1

### PR DESCRIPTION
**Pull request by xrotwang**
closes #193

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Looks good but do we need to add the final node label for the family? e.g. 

```
     tree glottolog_abkh1242 = (abkh1244:1,kaba1278:1); 
->
     tree glottolog_abkh1242 = (abkh1244:1,kaba1278:1)abkh1242:1; 
```

(also, the branch-length marking of `:1` is redundant)

**Comment by xrotwang** [comment]
Well, we do need internal node labels, and I guess the relevant newick
writer option also added the root label. The branch length is also
something that came with the newick format change. We could cycle through
the 9 ways of writing newick in ete3 to find something better. But we might
also live with this?

Am Mi., 12. Dez. 2018, 17:58 hat Simon J Greenhill <notifications@github.com>
geschrieben:

**Comment by SimonGreenhill** [comment]
Yes, can live with the branch lengths, but we're missing the root label - do you think it needs to be added?

**Comment by xrotwang** [comment]
Oh, I misunderstood. I thought you said we should get rid of the root
label. I think it's not needed anywhere so far.

Am Mi., 12. Dez. 2018, 18:05 hat Simon J Greenhill <notifications@github.com>
geschrieben:

**Comment by SimonGreenhill** [comment]
Ok, let's merge this and reopen if we do encounter the root edge problem in future.

**Pull request merged**
