### PR TITLE
first stab at a dplace-data curation package

### PR DESCRIPTION
**Pull request by xrotwang**
After running
```
python setup.py develop
```
you can run
```
$ dplace check
WARNING EA society Kela (Ae21) mapped to Bookkeeping language: kela1254
WARNING EA society Lalia (Ae23) mapped to Bookkeeping language: lali1242
WARNING Binford society Bambote (B62) without valid glottocode tempxx04
WARNING Binford society Sekele (B71) mapped to Bookkeeping language: oung1238
WARNING Binford society Undanbi (B114) without valid glottocode tempxx01
WARNING Binford society Nakako (B126) without valid glottocode tempxx03
```

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
Awesome! Can it check [this too](https://github.com/D-PLACE/dplace/issues/438)?

**Comment by xrotwang** [comment]
Regarding the "No matching society found" warnings, I propose a different approach: I just commited code which updated the TDWG region assignments for societies listed with one of the datasets. If the D-PLACE app loads the region data from [these assignemts](geo/societies_tdwg.json), it will only pick up societies which are actually coded in a dataset, thus the warnings would go away.

**Comment by xrotwang** [comment]
Btw. the code in `pydplace/geo.py` could also be used to compute assignment of TEOP ecoregion and biome to societies.

**Comment by SimonGreenhill** [comment]
Great! Keen to remove any non-essential warnings so that we don't ignore them.

**Comment by xrotwang** [comment]
ok. so I'll merge then.

**Comment by xrotwang** [comment]
And regarding moving code from dplace_app to pydplace: Yes! This was a constant experience for me in the last couple of years: Separating data curation from import in an app/database/whatever is such a big win in terms of transparency and maintainability. It allows to get rid of ever-growing monster-import scripts.

**Comment by SimonGreenhill** [comment]
Ok, we've only got 2 mapping issues now:

```
WARNING Binford society Bambote (B62) without valid glottocode tempxx04
WARNING Binford society Sekele (B71) mapped to Bookkeeping language: oung1238
```

...which I'll add as their own issues.

**Pull request merged**
