### PR TITLE
adding a check for the phylogenies directory

### PR DESCRIPTION
**Pull request by SimonGreenhill**

### CODE REVIEW

**Comment by xrotwang** [comment]
I came to prefer more declarative data validation like:
```python
@attr.s
class Society(UnicodeMixin):
    id = attr.ib()
    xd_id = attr.ib()
    pref_name_for_society = attr.ib()
    glottocode = attr.ib()
    ...
    Lat = attr.ib(convert=float, validator=partial(valid_range, -90, 90))
    Long = attr.ib(convert=float, validator=partial(valid_range, -180, 180))
    ...
```
This provides data validation upon access, which I think is good. It may take a bit more scaffolding to turn errors into meaningful messages, including line numbers and filenames and the like. But overall, I think this is a good model.

So once we settle on a schema for `taxa.csv` (?), I'd propose to turn this into a class, and add a `taxa` property to `Phylogeny`, which reads the rows from the csv into `Taxon` objects.

**Comment by xrotwang** [comment]
I guess, `taxon,xd_ids,soc_ids,glottocode` would cover all we have now in `xdid_socid_links.csv` and `languages.csv`.

**Comment by SimonGreenhill** [comment]
Ok -- this sounds good. The check function I've written will get unwieldy quickly when we add more checks, and having this done at the point at which the data enters the system makes sense. Are you able to implement this please?

**Comment by xrotwang** [comment]
Yes, will do. Later tonight, I guess.

**Pull request merged**
