### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by SimonGreenhill**
Went through commit log and extract most major changes. Look ok @xrotwang ?

### CODE REVIEW

**Review by xrotwang — APPROVED** [review]
We should make the release 1.2, though, right?

**Comment by SimonGreenhill** [comment]
yeah, I was a bit surprised at the large number of changes that have crept in since we last released! Hmm, looking at the releases page we've already done 2.1.0. Perhaps we should put all these changes under 2.2? or 3.0? (in which case the big refactor is v4 ?)

**Comment by xrotwang** [comment]
Ah, right, we are already at version 2.

**Comment by SimonGreenhill** [comment]
yeah, so what do you think - v 2.2 (and the big refactor is v 3?) or v 3 (and the big refactor is v4)?

**Comment by kirbykat** [comment]
My vote would be v2.2, with major refactor as 3. But happy to be out-voted.

**Comment by SimonGreenhill** [comment]
great, let's go with that. How's this?

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
