### PR TITLE
Added mapping for D301_Kare

### PR DESCRIPTION
**Pull request by xrotwang**
Based on name and classification in https://books.google.de/books?id=PQNHBQAAQBAJ&pg=PT803&lpg=PT803&dq=D301_Kare&source=bl&ots=gtEAiDl29i&sig=ACfU3U0Jjs4qgo_sxU9Gn8AgVKIKO0UwhA&hl=en&sa=X&ved=2ahUKEwjglqatj9vnAhWeSEEAHaxoBvIQ6AEwAXoECAUQAQ#v=onepage&q=D301_Kare&f=false
I think we can map D301_Kare to [Kari](https://glottolog.org/resource/languoid/id/kari1306)

### CODE REVIEW

**Comment by xrotwang** [comment]
@d97hah Do you think D301_Kare -> kari1306 is ok?

**Comment by d97hah** [comment]
Yes D301_Kare is kari1306. But just to double check, what's the original
source for assignment to D301_Kare?

Pada tanggal Sel, 18 Feb 2020 pukul 13.47 Robert Forkel <
notifications@github.com> menulis:

**Comment by xrotwang** [comment]
@d97hah I don't know, but I think a lot of the data from the Grollemund paper comes from Nurse and Philippson.

**Comment by d97hah** [comment]
Ok, that should be good enough for this.

Pada tanggal Sel, 18 Feb 2020 pukul 14.36 Robert Forkel <
notifications@github.com> menulis:

**Comment by SimonGreenhill** [comment]
👍

**Pull request merged**
