### PR TITLE
Resolve issue 184

### LINKED ISSUE #184: More minor updates.
@xrotwang, could you make this three, final, related changes - sorry not have included them before the last merge:

    xd1020 in the Binford societies.csv file should be replaced with xd1028 (there will no longer be an xd1020).

-glottolog_comment for the two societies with xd1020 (one in Binford, one in EA) should read:

"4Oct2018 - Note that while EA society Na11 has always been linked to xd1028, Binford society B379 was originally linked to xd1020 (and, thus, linked to the dialect "poin1245" and language "nort2943". The update to Glottolog 3.3.2 forced re-mapping of xd1028 from dialect "aiwa1238" (which no longer exists) to language "cent2128" (always the language-level match for this xd_id). "

-glottolog_comment for Binford B28 should read (if it does not already):

"1Oct2018 - the update to Glottolog 3.3.2 forced re-mapping from dialect chap1266 (which no longer exists) to language (cent2128) (always the language-level match for this society)."

If easier, these changes are present in this file (v3):
D-PLACE_society_to_xd_id_to_language_4Oct2018v3_UTF_8.zip

thanks again

(NOTE: edited to match my comments in https://github.com/D-PLACE/dplace-data/issues/183)

### PR DESCRIPTION
**Pull request by xrotwang**
closes #184

### CODE REVIEW

**Comment by xrotwang** [comment]
@kirbykat There was no EA society mapped to `xd1020` anymore.

**Comment by kirbykat** [comment]
@xrotwang yes- that is intentional. xd1020 will no longer exist, instead I realized that B379 == Na11 == xd1028.

**Comment by SimonGreenhill** [comment]
Looks good to me. Kate?

**Comment by kirbykat** [comment]
Yes, great. Thanks.

**Pull request merged**
