### PR TITLE
Work on references

### PR DESCRIPTION
**Pull request by xrotwang**
Please review, but don't merge yet. More to come after Glottolog lookup.

### CODE REVIEW

**Comment by xrotwang** [comment]
So, out of about 4,000 D-PLACE references I can find 762 matches in Glottolog. This isn't bad, I think, but still leaves a big chunk of work.
@SimonGreenhill should we still try to create BibTeX for all refs? The added value of being able to contribute these refs back to Glottolog may justify the effort. Still, this would probably need some student assistant work.

**Comment by SimonGreenhill** [comment]
Cool, thanks for the first-pass. Agree that it would be awesome (for everyone) if we can track down bibtex files. 

How do we handle this? a bibtex key column in references.csv which is currently empty but can be incrementally filled in later

**Comment by SimonGreenhill** [comment]
(sorry -- is this ready to merge? if not I'll back it out)

**Comment by xrotwang** [comment]
That's ok. I can merge master. I'd replace the csv with bibtex right away,
putting the whole citation into a field "raw" or similar. Then we could
refine this step by step.
Am 02.04.2017 10:26 schrieb "Simon J Greenhill" <notifications@github.com>:

**Comment by SimonGreenhill** [comment]
Only concern with replacing the text citations in csv is that it might make it more complicated for data collectors, and this is the format that it came in?

**Comment by xrotwang** [comment]
Ideally, future data would only need to reference existing records. But I
guess it boils down to whether we want to merge refs across datasets or
not. (and I'd say we want)
Am 03.04.2017 09:53 schrieb "Simon J Greenhill" <notifications@github.com>:

**Comment by xrotwang** [comment]
@SimonGreenhill Even if future references come in in the csv format, it shouldn't be too hard to at least trivially merge them into the BibTeX, adding records like
```
@misc{<dataset-id>:<key>
    key = {key},
    raw = {text citation}
}
```
until we turned all of this into structured data, we could even have the web app still import just the text citation (which may be created dynamically for complete BibTeX records). So all in all, I don't see this as a problem going forward.

**Pull request merged**
